Traceback (most recent call last):
  File "ParameterLoad.py", line 925, in <module>
    out=DeclareParameters(Sheetname,index)
  File "ParameterLoad.py", line 43, in DeclareParameters
    InBook     =wb.load_workbook(filename=SN,data_only=True)
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/openpyxl/reader/excel.py", line 314, in load_workbook
    data_only, keep_links)
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/openpyxl/reader/excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/openpyxl/reader/excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/zipfile.py", line 1226, in _RealGetContents
    raise BadZipFile("Bad magic number for central directory")
zipfile.BadZipFile: Bad magic number for central directory
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.727s
user	0m0.503s
sys	0m0.097s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.690s
user	0m0.520s
sys	0m0.073s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.715s
user	0m0.516s
sys	0m0.078s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.711s
user	0m0.504s
sys	0m0.089s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.714s
user	0m0.499s
sys	0m0.096s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.704s
user	0m0.500s
sys	0m0.097s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.705s
user	0m0.515s
sys	0m0.078s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.707s
user	0m0.496s
sys	0m0.100s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.705s
user	0m0.510s
sys	0m0.085s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.726s
user	0m0.509s
sys	0m0.088s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.712s
user	0m0.507s
sys	0m0.088s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.700s
user	0m0.507s
sys	0m0.088s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.706s
user	0m0.511s
sys	0m0.084s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.693s
user	0m0.515s
sys	0m0.080s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.699s
user	0m0.516s
sys	0m0.080s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.693s
user	0m0.512s
sys	0m0.081s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.696s
user	0m0.494s
sys	0m0.100s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.689s
user	0m0.515s
sys	0m0.079s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.690s
user	0m0.504s
sys	0m0.091s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.511s
sys	0m0.082s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.691s
user	0m0.493s
sys	0m0.105s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.509s
sys	0m0.083s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.521s
sys	0m0.073s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.511s
sys	0m0.081s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.749s
user	0m0.514s
sys	0m0.082s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.507s
sys	0m0.086s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.493s
sys	0m0.100s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.491s
sys	0m0.102s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.687s
user	0m0.519s
sys	0m0.076s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.496s
sys	0m0.096s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.687s
user	0m0.514s
sys	0m0.079s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.695s
user	0m0.520s
sys	0m0.073s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.689s
user	0m0.499s
sys	0m0.097s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.508s
sys	0m0.085s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.683s
user	0m0.514s
sys	0m0.079s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.497s
sys	0m0.098s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.689s
user	0m0.520s
sys	0m0.073s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.683s
user	0m0.494s
sys	0m0.098s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.695s
user	0m0.511s
sys	0m0.084s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.774s
user	0m0.500s
sys	0m0.094s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.696s
user	0m0.511s
sys	0m0.083s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.501s
sys	0m0.092s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.687s
user	0m0.496s
sys	0m0.099s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.687s
user	0m0.484s
sys	0m0.110s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.689s
user	0m0.500s
sys	0m0.096s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.704s
user	0m0.515s
sys	0m0.081s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.693s
user	0m0.498s
sys	0m0.096s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.490s
sys	0m0.104s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.687s
user	0m0.509s
sys	0m0.085s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.504s
sys	0m0.089s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.506s
sys	0m0.088s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.687s
user	0m0.512s
sys	0m0.082s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.690s
user	0m0.512s
sys	0m0.084s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.699s
user	0m0.505s
sys	0m0.090s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.761s
user	0m0.516s
sys	0m0.079s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.491s
sys	0m0.101s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.690s
user	0m0.502s
sys	0m0.092s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.684s
user	0m0.517s
sys	0m0.076s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.511s
sys	0m0.086s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.507s
sys	0m0.086s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.716s
user	0m0.507s
sys	0m0.088s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.719s
user	0m0.504s
sys	0m0.090s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.708s
user	0m0.501s
sys	0m0.096s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.514s
sys	0m0.079s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.515s
sys	0m0.079s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.501s
sys	0m0.093s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.503s
sys	0m0.091s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.760s
user	0m0.506s
sys	0m0.089s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.699s
user	0m0.506s
sys	0m0.089s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.697s
user	0m0.509s
sys	0m0.085s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.503s
sys	0m0.091s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.509s
sys	0m0.083s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.499s
sys	0m0.093s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.684s
user	0m0.507s
sys	0m0.087s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.696s
user	0m0.504s
sys	0m0.091s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.500s
sys	0m0.094s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.686s
user	0m0.517s
sys	0m0.077s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.688s
user	0m0.514s
sys	0m0.082s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.687s
user	0m0.523s
sys	0m0.071s
Traceback (most recent call last):
  File "RayTracerMainProgram.py", line 1168, in <module>
    main(sys.argv)
  File "RayTracerMainProgram.py", line 1119, in main
    parameters=  np.load('Parameters/Parameterarray.npy')
  File "/home/m/hw454/.conda/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Parameters/Parameterarray.npy'

real	0m0.685s
user	0m0.505s
sys	0m0.088s
